package assignmenthibernate;
// Generated 07.07.2019. 16:51:47 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.swing.JTextField;

/**
 * Employees generated by hbm2java
 */
@Entity
@Table(name = "employees",
         catalog = "employeesdb"
)
public class Employees implements java.io.Serializable {

    private Integer employeesId;
    private String name;
    private Integer age;
    private String address;
    private Integer salary;

    public Employees() {
    }

    public Employees(String name, Integer age, String address, Integer salary) {
        this.name = name;
        this.age = age;
        this.address = address;
        this.salary = salary;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "employees_id", unique = true, nullable = false)
    public Integer getEmployeesId() {
        return this.employeesId;
    }

    public void setEmployeesId(Integer employeesId) {
        this.employeesId = employeesId;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "age")
    public Integer getAge() {
        return this.age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    @Column(name = "address", length = 45)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "salary")
    public Integer getSalary() {
        return this.salary;
    }

    public void setSalary(Integer salary) {
        this.salary = salary;
    }

    public Employees(Integer employeesId, String name, Integer age, String address, Integer salary) {
        this.employeesId = employeesId;
        this.name = name;
        this.age = age;
        this.address = address;
        this.salary = salary;
    }
    

    @Override
    public String toString() {
        return 
                " ID" + employeesId + ", name : " + name + ", age=" + age + ", address=" + address + ", salary=" + salary + '\n';
    }

}
